server:
  port: 9100
spring:
  application:
    name: citicmall-user
#  datasource:
#      name: test
#      url: jdbc:mysql://127.0.0.1:3306/citic-shop
#      username: root
#      password: root
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: ejavashop
#    database: 0
#    # 连接超时时间（毫秒）
#    timeout: 30000
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9000/eureka/
#  instance:
#    prefer-ip-address: true

#mapper文件位置,model类路径
#mybatis:
#  mapper-locations: classpath:sql-mapper/**/*.xml
#  type-aliases-package: com.citicmall.model

#pagehelper分页插件
# pagehelper:
#   helperDialect: mysql
#   reasonable: true
#   supportMethodsArguments: true
#   params: count=countSql

#mybatis日志级别
#logging:
#  level:
#    com:
#      citicmall:
#        dao: debug
